export POWERLEVEL9K_INSTALLATION_DIR="$DOTFILES/deps/powerlevel9k"

export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time)

export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
export POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
export POWERLEVEL9K_SHORTEN_DELIMITER=""
export POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
export POWERLEVEL9K_STATUS_OK="" # Only show on error
export POWERLEVEL9K_USER_ICON="$"
export POWERLEVEL9K_ROOT_ICON="#"
export POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="25"
export POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="249"
export POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="25"
export POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="249"
export POWERLEVEL9K_DIR_HOME_BACKGROUND="25"
export POWERLEVEL9K_DIR_HOME_FOREGROUND="249"
