[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["dotfiles"]
    type = "git-repo"
    url = "git@github.com:three/dotfiles.git"
    refreshPeriod = "168h"
